apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - nodePort: 30800
      port: 8080
      targetPort: 3000
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: lb
#  labels:
#    name: lb
#spec:
#  ports:
#  - port: 80
#    targetPort: 3000
#  selector:
#    name: app
#  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:latest
          env:
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_INSTANCE_NAME
              value: "app"
            - name: MYSQL_PORT_3306_TCP_ADDR
              value: "mysql"
            - name: MYSQL_PORT_3306_TCP_PORT
              value: "3306"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000